# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_askedquestions_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askedquestions',
            name='slug',
            field=models.SlugField(),
        ),
    ]
