# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_auto_20170824_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askedquestions',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
