# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_auto_20170824_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askedquestions',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
